### ISSUE TITLE
[发布] 应用发布失败之20180517

### ISSUE THREAD

**Issue by fxleyu** [fxleyu/tux#36]
## 背景
昨天搭车上线，今天查看上线记录时有发布失败的问题。
- 压测分组的两台，全部发布失败。
- 广州分组中，大概一半全部发布失败。

简要查询原因，发现 log 信息类似，均是信息不全。

**Comment by fxleyu** [comment]
# 广州分组
## 1、查看服务端 log
查询服务端 log（`export\Logs\coffeesoa.leyu.com\serverside.log`），主要信息如下：
```
org.springframework.beans.factory.BeanCreationException: 
	Error creating bean with name 'userTracerWorker' defined in class path resource [spring-config-configcenter.xml]:
		Could not resolve matching constructor (hint: specify index/type/name arguments for simple parameters to avoid type ambiguities)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1049)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:953)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:490)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:295)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:292)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:439)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:429)
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1182)
```
log 的意思是找不到匹配的构造器参数导致的。
